FROM mysql:8.0

# Establecer variables de entorno si es necesario
ENV MYSQL_ROOT_PASSWORD=s3cr3t
ENV MYSQL_DATABASE=frutas-db
ENV MYSQL_USER=root
ENV MYSQL_PASSWORD=s3cr3t

# Exponer el puerto MySQL (opcional)
EXPOSE 3306